# Generated by Django 4.0.4 on 2022-06-03 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Image title')),
                ('slug', models.SlugField(blank=True, verbose_name='Image slug')),
                ('url', models.URLField(verbose_name='Image url')),
                ('image', models.ImageField(upload_to='', verbose_name='Picture')),
                ('description', models.TextField(max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_created', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('user_likes', models.ManyToManyField(blank=True, related_name='liked_images', to=settings.AUTH_USER_MODEL, verbose_name='likes')),
            ],
        ),
    ]
