# Generated by Django 4.0.4 on 2022-06-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Likes amount'),
        ),
    ]
