# Generated by Django 4.0.4 on 2022-06-16 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_options_alter_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Subscription time')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscription',
                'ordering': ['-subscribe_time'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='account.Subscription', to=settings.AUTH_USER_MODEL, verbose_name='Subscriptions'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Subscriber'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Sub'),
        ),
    ]
